# Copyright (C) 2013 The CyanogenMod Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/gm/discovery/setup-makefiles.sh


# -------------------------------------------------------------------
# PREBUILT LIBRARIES THAT ARE NEEDED TO BUILD OPEN-SOURCE LIBRARIES -
# -------------------------------------------------------------------
#!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
######################    DEPENDENCY SECTION  #######################
PRODUCT_COPY_FILES += \
    vendor/gm/discovery/proprietary/lib/libril.so:obj/lib/libril.so \
    vendor/gm/discovery/proprietary/lib/librilmtk.so:obj/lib/librilmtk.so


#!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
###################### DON'T EDIT ###################################
PRODUCT_COPY_FILES += \
    vendor/gm/discovery/proprietary/bin/mtkGD:system/bin/mtkGD \
    vendor/gm/discovery/proprietary/vendor/bin/pvrsrvctl:system/vendor/bin/pvrsrvctl \
    vendor/gm/discovery/proprietary/vendor/bin/rc.fac:system/vendor/bin/rc.fac \
    vendor/gm/discovery/proprietary/vendor/lib/drm/libdrmwvmplugin.so:system/vendor/lib/drm/libdrmwvmplugin.so \
    vendor/gm/discovery/proprietary/vendor/lib/egl/libEGL_mtk.so:system/vendor/lib/egl/libEGL_mtk.so \
    vendor/gm/discovery/proprietary/vendor/lib/egl/libGLESv1_CM_mtk.so:system/vendor/lib/egl/libGLESv1_CM_mtk.so \
    vendor/gm/discovery/proprietary/vendor/lib/egl/libGLESv2_mtk.so:system/vendor/lib/egl/libGLESv2_mtk.so \
    vendor/gm/discovery/proprietary/vendor/lib/hw/gralloc.mt6589.so:system/vendor/lib/hw/gralloc.mt6589.so \
    vendor/gm/discovery/proprietary/vendor/lib/libBLPP.so:system/vendor/lib/libBLPP.so \
    vendor/gm/discovery/proprietary/vendor/lib/libIMGegl.so:system/vendor/lib/libIMGegl.so \
    vendor/gm/discovery/proprietary/vendor/lib/libPVRScopeServices.so:system/vendor/lib/libPVRScopeServices.so \
    vendor/gm/discovery/proprietary/vendor/lib/libWVStreamControlAPI_L3.so:system/vendor/lib/libWVStreamControlAPI_L3.so \
    vendor/gm/discovery/proprietary/vendor/lib/libglslcompiler.so:system/vendor/lib/libglslcompiler.so \
    vendor/gm/discovery/proprietary/vendor/lib/libpvr2d.so:system/vendor/lib/libpvr2d.so \
    vendor/gm/discovery/proprietary/vendor/lib/libpvrANDROID_WSEGL.so:system/vendor/lib/libpvrANDROID_WSEGL.so \
    vendor/gm/discovery/proprietary/vendor/lib/libsrv_init.so:system/vendor/lib/libsrv_init.so \
    vendor/gm/discovery/proprietary/vendor/lib/libsrv_um.so:system/vendor/lib/libsrv_um.so \
    vendor/gm/discovery/proprietary/vendor/lib/libusc.so:system/vendor/lib/libusc.so \
    vendor/gm/discovery/proprietary/vendor/lib/libwvdrm_L3.so:system/vendor/lib/libwvdrm_L3.so \
    vendor/gm/discovery/proprietary/vendor/lib/libwvm.so:system/vendor/lib/libwvm.so \
    vendor/gm/discovery/proprietary/lib/libMtkOmxAMRNBDec.so:system/lib/libMtkOmxAMRNBDec.so \
    vendor/gm/discovery/proprietary/lib/libMtkOmxAMRWBDec.so:system/lib/libMtkOmxAMRWBDec.so \
    vendor/gm/discovery/proprietary/lib/libMtkOmxAacDec.so:system/lib/libMtkOmxAacDec.so \
    vendor/gm/discovery/proprietary/lib/libMtkOmxAacEnc.so:system/lib/libMtkOmxAacEnc.so \
    vendor/gm/discovery/proprietary/lib/libMtkOmxAdpcmDec.so:system/lib/libMtkOmxAdpcmDec.so \
    vendor/gm/discovery/proprietary/lib/libMtkOmxAdpcmEnc.so:system/lib/libMtkOmxAdpcmEnc.so \
    vendor/gm/discovery/proprietary/lib/libMtkOmxAmrEnc.so:system/lib/libMtkOmxAmrEnc.so \
    vendor/gm/discovery/proprietary/lib/libMtkOmxApeDec.so:system/lib/libMtkOmxApeDec.so \
    vendor/gm/discovery/proprietary/lib/libMtkOmxAwbEnc.so:system/lib/libMtkOmxAwbEnc.so \
    vendor/gm/discovery/proprietary/lib/libMtkOmxCore.so:system/lib/libMtkOmxCore.so \
    vendor/gm/discovery/proprietary/lib/libMtkOmxFlacDec.so:system/lib/libMtkOmxFlacDec.so \
    vendor/gm/discovery/proprietary/lib/libMtkOmxG711Dec.so:system/lib/libMtkOmxG711Dec.so \
    vendor/gm/discovery/proprietary/lib/libMtkOmxMp3Dec.so:system/lib/libMtkOmxMp3Dec.so \
    vendor/gm/discovery/proprietary/lib/libMtkOmxVdec.so:system/lib/libMtkOmxVdec.so \
    vendor/gm/discovery/proprietary/lib/libMtkOmxVenc.so:system/lib/libMtkOmxVenc.so \
    vendor/gm/discovery/proprietary/lib/libMtkOmxVorbisDec.so:system/lib/libMtkOmxVorbisDec.so \
    vendor/gm/discovery/proprietary/lib/libMtkOmxVorbisEnc.so:system/lib/libMtkOmxVorbisEnc.so \
    vendor/gm/discovery/proprietary/etc/firmware/modem.img:system/etc/firmware/modem.img \
    vendor/gm/discovery/proprietary/etc/mddb/BPLGUInfoCustomAppSrcP_MT6589_S00_MOLY_WR8_W1248_MD_WG_MP_V6_P26:system/etc/mddb/BPLGUInfoCustomAppSrcP_MT6589_S00_MOLY_WR8_W1248_MD_WG_MP_V6_P26 \
    vendor/gm/discovery/proprietary/bin/xlog:system/bin/xlog \
    vendor/gm/discovery/proprietary/lib/libril.so:system/lib/libril.so \
    vendor/gm/discovery/proprietary/lib/librilmtk.so:system/lib/librilmtk.so \
    vendor/gm/discovery/proprietary/lib/mtk-ril.so:system/lib/mtk-ril.so \
    vendor/gm/discovery/proprietary/lib/libnvram.so:system/lib/libnvram.so \
    vendor/gm/discovery/proprietary/lib/libcustom_nvram.so:system/lib/libcustom_nvram.so \
    vendor/gm/discovery/proprietary/bin/6620_launcher:system/bin/6620_launcher \
    vendor/gm/discovery/proprietary/bin/wlan_loader:system/bin/wlan_loader \
    vendor/gm/discovery/proprietary/lib/libdpframework.so:system/lib/libdpframework.so \
    vendor/gm/discovery/proprietary/lib/libdpframework_os.so:system/lib/libdpframework_os.so \
    vendor/gm/discovery/proprietary/lib/libdpframework_plat.so:system/lib/libdpframework_plat.so \
    vendor/gm/discovery/proprietary/lib/hw/gralloc.default.so:system/lib/hw/gralloc.default.so \
    vendor/gm/discovery/proprietary/lib/hw/hwcomposer.mt6589.so:system/lib/hw/hwcomposer.mt6589.so \
    vendor/gm/discovery/proprietary/lib/libaed.so:system/lib/libaed.so \
    vendor/gm/discovery/proprietary/lib/libaudiocustparam.so:system/lib/libaudiocustparam.so \
    vendor/gm/discovery/proprietary/lib/libaudiosetting.so:system/lib/libaudiosetting.so \
    vendor/gm/discovery/proprietary/lib/libtinyalsa.so:system/lib/libtinyalsa.so \
    vendor/gm/discovery/proprietary/lib/libcam.camadapter.so:system/lib/libcam.camadapter.so \
    vendor/gm/discovery/proprietary/lib/libcam.campipe.so:system/lib/libcam.campipe.so \
    vendor/gm/discovery/proprietary/lib/libcam.camshot.so:system/lib/libcam.camshot.so \
    vendor/gm/discovery/proprietary/lib/libcam.client.so:system/lib/libcam.client.so \
    vendor/gm/discovery/proprietary/lib/libcam.paramsmgr.so:system/lib/libcam.paramsmgr.so \
    vendor/gm/discovery/proprietary/lib/libcam.utils.so:system/lib/libcam.utils.so \
    vendor/gm/discovery/proprietary/lib/libcamalgo.so:system/lib/libcamalgo.so \
    vendor/gm/discovery/proprietary/lib/libcamdrv.so:system/lib/libcamdrv.so \
    vendor/gm/discovery/proprietary/lib/libcamera_jni_eglfence.so:system/lib/libcamera_jni_eglfence.so \
    vendor/gm/discovery/proprietary/lib/libfeatureio.so:system/lib/libfeatureio.so \
    vendor/gm/discovery/proprietary/lib/libimageio.so:system/lib/libimageio.so \
    vendor/gm/discovery/proprietary/lib/libion.so:system/lib/libion.so \
    vendor/gm/discovery/proprietary/lib/libcam_camera_exif.so:system/lib/libcam_camera_exif.so \
    vendor/gm/discovery/proprietary/lib/libJpgDecPipe.so:system/lib/libJpgDecPipe.so \
    vendor/gm/discovery/proprietary/lib/libJpgEncPipe.so:system/lib/libJpgEncPipe.so \
    vendor/gm/discovery/proprietary/lib/libcameracustom.so:system/lib/libcameracustom.so \
    vendor/gm/discovery/proprietary/lib/libgn_camera_feature.so:system/lib/libgn_camera_feature.so \
    vendor/gm/discovery/proprietary/lib/libm4u.so:system/lib/libm4u.so \
    vendor/gm/discovery/proprietary/lib/libmatv_cust.so:system/lib/libmatv_cust.so \
    vendor/gm/discovery/proprietary/lib/libmpo.so:system/lib/libmpo.so \
    vendor/gm/discovery/proprietary/lib/libmpoencoder.so:system/lib/libmpoencoder.so \
    vendor/gm/discovery/proprietary/lib/libtouchless_a3d.so:system/lib/libtouchless_a3d.so \
    vendor/gm/discovery/proprietary/lib/hw/audio.primary.default.so:system/lib/hw/audio.primary.default.so \
    vendor/gm/discovery/proprietary/lib/hw/audio_policy.default.so:system/lib/hw/audio_policy.default.so \
    vendor/gm/discovery/proprietary/lib/hw/audio_policy.stub.so:system/lib/hw/audio_policy.stub.so \
    vendor/gm/discovery/proprietary/lib/hw/libaudio.r_submix.default.so:system/lib/hw/libaudio.r_submix.default.so \
    vendor/gm/discovery/proprietary/lib/hw/libaudio.usb.default.so:system/lib/hw/libaudio.usb.default.so \
    vendor/gm/discovery/proprietary/lib/hw/camera.default.so:system/lib/hw/camera.default.so \
    vendor/gm/discovery/proprietary/bin/surfaceflinger:system/bin/surfaceflinger \
    vendor/gm/discovery/proprietary/lib/libui.so:system/lib/libui.so \
    vendor/gm/discovery/proprietary/lib/libgui.so:system/lib/libgui.so \
    vendor/gm/discovery/proprietary/lib/libsurfaceflinger.so:system/lib/libsurfaceflinger.so \
    vendor/gm/discovery/proprietary/lib/libbinder.so:system/lib/libbinder.so \
    vendor/gm/discovery/proprietary/lib/libmedia.so:system/lib/libmedia.so \
    vendor/gm/discovery/proprietary/lib/libstagefright.so:system/lib/libstagefright.so \
    vendor/gm/discovery/proprietary/lib/libstagefright_memutil.so:system/lib/libstagefright_memutil.so \
    vendor/gm/discovery/proprietary/lib/libstagefright_omx.so:system/lib/libstagefright_omx.so \
    vendor/gm/discovery/proprietary/lib/libstagefright_wfd.so:system/lib/libstagefright_wfd.so \
    vendor/gm/discovery/proprietary/lib/libcamera_client.so:system/lib/libcamera_client.so \
    vendor/gm/discovery/proprietary/lib/libcamera_metadata.so:system/lib/libcamera_metadata.so \
    vendor/gm/discovery/proprietary/lib/hw/gps.default.so:system/lib/hw/gps.default.so \
    vendor/gm/discovery/proprietary/lib/hw/keystore.default.so:system/lib/hw/keystore.default.so \
    vendor/gm/discovery/proprietary/lib/hw/lights.default.so:system/lib/hw/lights.default.so \
    vendor/gm/discovery/proprietary/lib/hw/local_time.default.so:system/lib/hw/local_time.default.so \
    vendor/gm/discovery/proprietary/lib/hw/power.default.so:system/lib/hw/power.default.so \
    vendor/gm/discovery/proprietary/lib/hw/sensors.default.so:system/lib/hw/sensors.default.so \
    vendor/gm/discovery/proprietary/etc/firmware/S_ANDRO_SFL.ini:system/etc/firmware/S_ANDRO_SFL.ini \
    vendor/gm/discovery/proprietary/etc/firmware/WIFI_RAM_CODE:system/etc/firmware/WIFI_RAM_CODE \
    vendor/gm/discovery/proprietary/etc/firmware/WIFI_RAM_CODE_E6:system/etc/firmware/WIFI_RAM_CODE_E6 \
    vendor/gm/discovery/proprietary/etc/firmware/WIFI_RAM_CODE_MT6628:system/etc/firmware/WIFI_RAM_CODE_MT6628 \
    vendor/gm/discovery/proprietary/etc/firmware/WMT.cfg:system/etc/firmware/WMT.cfg \
    vendor/gm/discovery/proprietary/etc/firmware/catcher_filter.bin:system/etc/firmware/catcher_filter.bin \
    vendor/gm/discovery/proprietary/etc/firmware/mt6628_ant_m1.cfg:system/etc/firmware/mt6628_ant_m1.cfg \
    vendor/gm/discovery/proprietary/etc/firmware/mt6628_patch_e1_hdr.bin:system/etc/firmware/mt6628_patch_e1_hdr.bin \
    vendor/gm/discovery/proprietary/etc/firmware/mt6628_patch_e2_0_hdr.bin:system/etc/firmware/mt6628_patch_e2_0_hdr.bin \
    vendor/gm/discovery/proprietary/etc/firmware/mt6628_patch_e2_1_hdr.bin:system/etc/firmware/mt6628_patch_e2_1_hdr.bin \
    vendor/gm/discovery/proprietary/etc/firmware/mt6628/mt6628_fm_rom.bin:system/etc/firmware/mt6628/mt6628_fm_rom.bin \
    vendor/gm/discovery/proprietary/etc/firmware/mt6628/mt6628_fm_v1_coeff.bin:system/etc/firmware/mt6628/mt6628_fm_v1_coeff.bin \
    vendor/gm/discovery/proprietary/etc/firmware/mt6628/mt6628_fm_v1_patch.bin:system/etc/firmware/mt6628/mt6628_fm_v1_patch.bin \
    vendor/gm/discovery/proprietary/etc/firmware/mt6628/mt6628_fm_v2_coeff.bin:system/etc/firmware/mt6628/mt6628_fm_v2_coeff.bin \
    vendor/gm/discovery/proprietary/etc/firmware/mt6628/mt6628_fm_v2_patch.bin:system/etc/firmware/mt6628/mt6628_fm_v2_patch.bin \
    vendor/gm/discovery/proprietary/etc/firmware/mt6628/mt6628_fm_v3_coeff.bin:system/etc/firmware/mt6628/mt6628_fm_v3_coeff.bin \
    vendor/gm/discovery/proprietary/etc/firmware/mt6628/mt6628_fm_v3_patch.bin:system/etc/firmware/mt6628/mt6628_fm_v3_patch.bin \
    vendor/gm/discovery/proprietary/etc/firmware/mt6628/mt6628_fm_v4_coeff.bin:system/etc/firmware/mt6628/mt6628_fm_v4_coeff.bin \
    vendor/gm/discovery/proprietary/etc/firmware/mt6628/mt6628_fm_v4_patch.bin:system/etc/firmware/mt6628/mt6628_fm_v4_patch.bin \
    vendor/gm/discovery/proprietary/etc/firmware/mt6628/mt6628_fm_v5_coeff.bin:system/etc/firmware/mt6628/mt6628_fm_v5_coeff.bin \
    vendor/gm/discovery/proprietary/etc/firmware/mt6628/mt6628_fm_v5_patch.bin:system/etc/firmware/mt6628/mt6628_fm_v5_patch.bin \
    vendor/gm/discovery/proprietary/lib/modules/ccci.ko:system/lib/modules/ccci.ko \
    vendor/gm/discovery/proprietary/lib/modules/ccci_plat.ko:system/lib/modules/ccci_plat.ko \
    vendor/gm/discovery/proprietary/lib/modules/devapc.ko:system/lib/modules/devapc.ko \
    vendor/gm/discovery/proprietary/lib/modules/devinfo.ko:system/lib/modules/devinfo.ko \
    vendor/gm/discovery/proprietary/lib/modules/hid-logitech-dj.ko:system/lib/modules/hid-logitech-dj.ko \
    vendor/gm/discovery/proprietary/lib/modules/mtk_fm_drv.ko:system/lib/modules/mtk_fm_drv.ko \
    vendor/gm/discovery/proprietary/lib/modules/mtk_hif_sdio.ko:system/lib/modules/mtk_hif_sdio.ko \
    vendor/gm/discovery/proprietary/lib/modules/mtk_stp_bt.ko:system/lib/modules/mtk_stp_bt.ko \
    vendor/gm/discovery/proprietary/lib/modules/mtk_stp_gps.ko:system/lib/modules/mtk_stp_gps.ko \
    vendor/gm/discovery/proprietary/lib/modules/mtk_stp_uart.ko:system/lib/modules/mtk_stp_uart.ko \
    vendor/gm/discovery/proprietary/lib/modules/mtk_stp_wmt.ko:system/lib/modules/mtk_stp_wmt.ko \
    vendor/gm/discovery/proprietary/lib/modules/mtk_wmt_wifi.ko:system/lib/modules/mtk_wmt_wifi.ko \
    vendor/gm/discovery/proprietary/lib/modules/mtklfb.ko:system/lib/modules/mtklfb.ko \
    vendor/gm/discovery/proprietary/lib/modules/pvrsrvkm.ko:system/lib/modules/pvrsrvkm.ko \
    vendor/gm/discovery/proprietary/lib/modules/scsi_tgt.ko:system/lib/modules/scsi_tgt.ko \
    vendor/gm/discovery/proprietary/lib/modules/scsi_wait_scan.ko:system/lib/modules/scsi_wait_scan.ko \
    vendor/gm/discovery/proprietary/lib/modules/sec.ko:system/lib/modules/sec.ko \
    vendor/gm/discovery/proprietary/lib/modules/vcodec_kernel_driver.ko:system/lib/modules/vcodec_kernel_driver.ko \
    vendor/gm/discovery/proprietary/lib/modules/wlan.ko:system/lib/modules/wlan.ko \
    vendor/gm/discovery/proprietary/lib/modules/wlan_mt6628.ko:system/lib/modules/wlan_mt6628.ko
